# 로컬환경입니다. application-local.yml
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://database-1.cp0caokgorxg.ap-northeast-2.rds.amazonaws.com:3306/test?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: a1234567
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

springdoc:
  swagger-ui:
    path: /